name: Manual Re-Deploy from GH-Pages data

on:
  workflow_dispatch:

jobs:
  redeploy:
    name: Manual Re-Deploy by workflow dispatch
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.author.name, 'dependabot')" # ignore dependabot
    steps:
      - uses: volta-cli/action@v3.0.2
      - name: Install Surge via volta
        run: volta install node && volta install surge

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: dist

      - name: Deploy to surge.sh (Backup)
        uses: dswistowski/surge-sh-action@v1.0.2
        with:
          domain: '${{ secrets.surge_domain }}'
          project: './dist'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}